# NOTE: update this with your service name
service: helloworld-service

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    ITEMS_TABLE_NAME: ${self:custom.ItemsTable.name}
  iamRoleStatements:
    - ${file(iam/ItemsTableIAM.yml):ItemsTableIAM}

  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

resources:
  Resources:
    ItemsTable: ${file(resources/ItemsTable.yml):ItemsTable}

functions:
  createItem:
    handler: src/handlers/createItem.handler
    events:
      - http:
          method: POST
          path: /item

  getItems:
    handler: src/handlers/getItems.handler
    events:
      - http:
          method: GET
          path: /items

  getItem:
    handler: src/handlers/getItem.handler
    events:
      - http:
          method: GET
          path: /item/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /item/{id}/bid

custom:
  ItemsTable:
    name: !Ref ItemsTable
    arn: !GetAtt ItemsTable.Arn
